"""empty message

Revision ID: a2c52d9a8132
Revises: 
Create Date: 2026-03-11 17:40:53.138706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c52d9a8132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('zone_type', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('location_zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('first_account_id', sa.Integer(), nullable=False),
    sa.Column('race_choice_id', sa.Integer(), nullable=True),
    sa.Column('class_base_choice_id', sa.Integer(), nullable=True),
    sa.Column('location_character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_base_choice_id'], ['class_base.id'], ),
    sa.ForeignKeyConstraint(['first_account_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_character_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['race_choice_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendship_from_character_id', sa.Integer(), nullable=False),
    sa.Column('friendship_to_character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friendship_from_character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['friendship_to_character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    op.drop_table('character')
    op.drop_table('location')
    op.drop_table('zone')
    op.drop_table('user')
    op.drop_table('race')
    op.drop_table('class_base')
    # ### end Alembic commands ###
